### ISSUE TITLE
cpu, ram?

### ISSUE THREAD

**Issue by Vladimir855** [Mizogg/4Bitcoin-pySimpleGUI#1]
Привет, сколько мощности потребляют твои скрипты (в целом), cpu, ram?

**Comment by Mizogg** [comment]
They use very low CPU. There is no Multi Threading or Processing in these python programs. The size of your database/list off addresses you are looking for will change the ammount of memory needed. 1Gb Database will use between 3.5-4Gb RAM and will take longer to start. smaller the Database the quicker it loads and less RAM used

**Comment by Vladimir855** [comment]
На Ubuntu запускаются ваши скрипты?

**Comment by Mizogg** [comment]
No most of mine I run under Windows 10/11 in Command prompt or power shell. I have Installed WSL Windows Subsystem for Linux, Ubuntu and python. Ubuntu Install https://mizogg.co.uk/ubuntuinstall/ and Python3.9 Installation https://mizogg.co.uk/cmder/. Also check https://github.com/Mizogg from other items needed to install to run programs.  

Большую часть своих я запускаю под Windows 10/11 в командной строке или в оболочке питания. Я установил подсистему WSL Windows для Linux, Ubuntu и python. Установка Ubuntu https://mizogg.co.uk/ubuntuinstall/ и установка Python3.9 https://mizogg.co.uk/cmder/. Также проверьте https://github.com/Mizogg на предмет других элементов, необходимых для установки для запуска программ.
